# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.roastLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.roastLineEdit.setObjectName("roastLineEdit")
        self.verticalLayout.addWidget(self.roastLineEdit)
        self.typeComboBox = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.verticalLayout.addWidget(self.typeComboBox)
        self.descriptionLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.verticalLayout.addWidget(self.descriptionLineEdit)
        self.priceLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.verticalLayout.addWidget(self.priceLineEdit)
        self.volumeLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.volumeLineEdit.setObjectName("volumeLineEdit")
        self.verticalLayout.addWidget(self.volumeLineEdit)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.nameLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.roastLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Степень обжарки"))
        self.typeComboBox.setItemText(0, _translate("AddEditCoffeeForm", "Молотый"))
        self.typeComboBox.setItemText(1, _translate("AddEditCoffeeForm", "В зернах"))
        self.descriptionLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.priceLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Цена"))
        self.volumeLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Объем упаковки (г)"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Отмена"))
